version: '2'
services:
  web:
    build: docker build -t docker-app/node-web-app .
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"